### ISSUE TITLE
Roadmap 2023 Q1

### ISSUE THREAD

**Issue by lihebi** [codepod-io/codepod#208]
## P1 Roadmap: the most important features missing
- [x] various UI issues mentioned in #181 
- [ ] (@lihebi, WIP) Local runtime #212
- [x] (@lihebi , WIP) .ipynb & .py file import/export and sync with github #211
- [ ] Version control
- [x] Auto-layout
- [ ] Mount drive
- [x] Save outputs: potential issues: output too large (e.g. image) to send via GraphQL query.
- [x] Chain-of-pods execution: and persist the arrows to database #210 
- [ ] minimap with ToC for jumping nodes
- [x] (@li-xin-yi) #213
- [x] (@li-xin-yi) copy-n-paste a scope #114 
- [ ] (@li-xin-yi) fine-grained access control #177 
- [ ] (@li-xin-yi) record user-project data such as lastViewPoint #157 

## P2 roadmap
- [ ] Better Local release for those who are not into cloud
- [ ] Add comment
- [x] Latex support in rich text editor
- [ ] issue tracking
- [ ] CI/CD
- [ ] runtime for more languages

## Backend roadmap: the improvements under-the-hood
- [x] Yjs server routing & auth & highly-availability
- [ ] Separate server from runtime & storage server

**Comment by forrestbao** [comment]
1. What's the relationship between "Local runtime" in P1 and "Better Local release for those who are not into cloud" in P2? 
2. Q1 is a very long time, 3 months. Can we set timeline for the tasks?

**Comment by lihebi** [comment]
> 1. What's the relationship between "Local runtime" in P1 and "Better Local release for those who are not into cloud" in P2?
- **local runtime**: This is about the locally launched runtime kernel. This is especially useful when they want to use their GPU machines. Users still write code on https://codepod.io, so they can share with others and collaborate in real-time. They won't need to worry about data storage and backup as well.
- **local release**: The app is deployed entirely offline. The current local deployment requires docker and save code in a database. A desired local release would be a local app with a file-based backend for persistence. But this is not our priority.

> 2. Q1 is a very long time, 3 months. Can we set a timeline for the tasks?

Let's keep refining the timeline.

**Comment by li-xin-yi** [comment]
You can use [projects](https://docs.github.com/en/issues/planning-and-tracking-with-projects/learning-about-projects/about-projects) to manage the progress of those features.

**Comment by forrestbao** [comment]
I'd wanna add one more: something like ToC for users to quick jump between different parts of the program. Paging up and down is a major reason that development in Jupyter is slow. We cannot let users pan, scroll, or zoom to find what they want.

**Comment by lihebi** [comment]
> You can use [projects](https://docs.github.com/en/issues/planning-and-tracking-with-projects/learning-about-projects/about-projects) to manage the progress of those features.

I did try "project" several times in the past, but I found it overkill / hard-to-use (confusing issue linking, no comment, no markdown, weak timestamp tracking, and the multi-columns view seems complicated). It's probably more suitable when we have a larger team.

**Comment by lihebi** [comment]
> ToC for users to quick jump between different parts of the program

Agreed; added the ToC/minimap to the P1 roadmap.

**Comment by lihebi** [comment]
> You can use [projects](https://docs.github.com/en/issues/planning-and-tracking-with-projects/learning-about-projects/about-projects) to manage the progress of those features.

One more thing: I'm working on export-and-sync-to-github (#211). Once that is done, we'll move many of the project docs & progress management to a public/shared codepod repo.
