### ISSUE TITLE
Grand opening (ETA Sep 2023) checklist

### ISSUE THREAD

**Issue by lihebi** [codepod-io/codepod#333]
For the grand opening, we need to make sure the servers are properly structured:

Majors:
- [x] @lihebi #331 
- [x] @lihebi #332 
- [x] @lihebi Local desktop app with file-backend to be compatible with VSCode workflow
- [x] @lihebi native runtime #501 
- [ ] Selective View for scaling

Minors:
* [ ] multiple language kernels
* [ ] cross-language runtime
* [ ] more arrow types
* [ ] [note-taking] more node types: image, video, pdf
* [ ] [note-taking] import pdfs (e.g., for slides)

Company goals:
* [ ] paper revision
* [ ] pricing plans & enterprise cloud & security & privacy

Other:

- [x] Hopping between pods/scopes completely in keyboard operations (https://github.com/codepod-io/codepod/issues/88 and https://github.com/codepod-io/codepod/issues/87). Partially done in #327. 
- ~Better auto-layout~ https://github.com/codepod-io/codepod/issues/338
- ~Better contextual zooming~, including #307, #316, and #317 
- [x] #167

Mostly done with pending bugs: 
- Import and export from and to Jupyter and Python files.  https://github.com/codepod-io/codepod/issues/411 https://github.com/codepod-io/codepod/pull/343  https://github.com/codepod-io/codepod/pull/399 https://github.com/codepod-io/codepod/pull/369

Minors or stretch goals
- Simple snapshot-based history, undo and redo. 
- One button to run the entire notebook
- Buffer pip-installed packages 
- A file browser

**Comment by lihebi** [comment]
The CLI app in this repo is ready to release to the general public.

Install:

```
> npm install -g codepod
```

Use:

```
> codepod /path/to/repo
# ... 🚀 Server ready at http://localhost:4001
```

Open this URL in your browser to see the app.

Features:
1. Local file saving: The files will be saved to the directory /path/to/repo/codepod.bin|json. The codepod.bin is the source of truth, and codepod.json is for human-readability only.
2. Local runtime: the spawner will use the Python and ipykernel installed on your host system. You can directly use your GPU server.

**Comment by lihebi** [comment]
We're not going to really "grand-open" by "advertising" it though, because we're switching to developing the SaaS app further.
